apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus
        imagePullPolicy: Always
        name: prometheus
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: config
      volumes:
      - configMap:
          name: prometheus
        name: config
---
apiVersion: v1
data:
  prometheus.yml: " # my global config\nglobal:\n  scrape_interval: 15s # Set the
    scrape interval to every 15 seconds. Default is every 1 minute.\n  evaluation_interval:
    15s # Evaluate rules every 15 seconds. The default is every 1 minute.\n  # scrape_timeout
    is set to the global default (10s).\n\n# Alertmanager configuration\nalerting:\n
    \ alertmanagers:\n    - static_configs:\n        - targets:\n          # - alertmanager:9093\n\n#
    Load rules once and periodically evaluate them according to the global 'evaluation_interval'.\nrule_files:\n
    \ # - \"first_rules.yml\"\n  # - \"second_rules.yml\"\n\n# A scrape configuration
    containing exactly one endpoint to scrape:\n# Here it's Prometheus itself.\nscrape_configs:\n
    \ # The job name is added as a label `job=<job_name>` to any timeseries scraped
    from this config.\n  - job_name: \"prometheus\"\n\n    # metrics_path defaults
    to '/metrics'\n    # scheme defaults to 'http'.\n\n    static_configs:\n      -
    targets: [\"localhost:9090\", \"otoflask\", \"otoflask-canary\"]\n      \n"
kind: ConfigMap
metadata:
  name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
