apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: rollouts-service
spec:
  weighted:
    services:
      - name: rollouts-demo # k8s service name that you need to create for stable application version
        port: 80
      - name: rollouts-demo-canary # k8s service name that you need to create for new application version
        port: 80
